#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

input="samples/raw/big-buck-bunny-1080p-normal.mp4"
ladder_dir=""
output_dir="samples/generated/hls"
segment_seconds="${HLS_SEGMENT_SECONDS:-6}"
overwrite=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --input|-i) [[ $# -ge 2 ]] || usage_error "$1 requires a value"; input="$2"; shift 2 ;;
    --ladder-dir) [[ $# -ge 2 ]] || usage_error "--ladder-dir requires a value"; ladder_dir="$2"; shift 2 ;;
    --output-dir|-o) [[ $# -ge 2 ]] || usage_error "$1 requires a value"; output_dir="$2"; shift 2 ;;
    --segment-seconds) [[ $# -ge 2 ]] || usage_error "--segment-seconds requires a value"; segment_seconds="$2"; shift 2 ;;
    --overwrite) overwrite=true; shift ;;
    -h|--help)
      cat <<'EOF'
Generate a VOD HLS master playlist and aligned variant playlists.

Usage: scripts/generate-hls.sh [--input PATH] [--ladder-dir PATH]
                               [--output-dir PATH] [--segment-seconds N]
                               [--overwrite]

Without --ladder-dir the fixed ladder is generated first. Existing output is
kept unless --overwrite is supplied.
EOF
      media_help
      exit 0
      ;;
    *) usage_error "unknown argument: $1" ;;
  esac
done

input="$(workspace_file "$input")"
output_dir="$(workspace_file "$output_dir")"
if [[ -n "$ladder_dir" ]]; then
  ladder_dir="$(workspace_file "$ladder_dir")"
else
  ladder_dir="$output_dir/.ladder"
  mkdir -p "$ladder_dir"
  ladder_args=(--input "$input" --output-dir "$ladder_dir")
  [[ "$overwrite" == true ]] && ladder_args+=(--overwrite)
  "$SCRIPT_DIR/generate-ladder.sh" "${ladder_args[@]}"
fi

[[ -d "$ladder_dir" ]] || die "ladder directory not found: $ladder_dir"
mkdir -p "$output_dir"

profiles=("240 426 240 400000" "360 640 360 800000" "480 854 480 1200000" "720 1280 720 2500000" "1080 1920 1080 5000000")
master="$output_dir/master.m3u8"
printf '#EXTM3U\n#EXT-X-VERSION:3\n# Generated by scripts/generate-hls.sh\n' > "$master"

for profile in "${profiles[@]}"; do
  read -r height width resolution bandwidth <<< "$profile"
  rendition="$ladder_dir/${height}p.mp4"
  [[ -f "$rendition" ]] || continue
  variant_dir="$output_dir/${height}p"
  mkdir -p "$variant_dir"
  playlist="$variant_dir/index.m3u8"
  if [[ -f "$playlist" && "$overwrite" == false ]]; then
    printf 'exists, skipping: %s\n' "$playlist"
  else
    run_media ffmpeg -hide_banner -loglevel warning -y -i "$rendition" -map 0 \
      -c copy -f hls -hls_time "$segment_seconds" -hls_playlist_type vod \
      -hls_flags independent_segments -hls_segment_filename "$variant_dir/segment_%05d.ts" \
      "$playlist"
  fi
  printf '#EXT-X-STREAM-INF:BANDWIDTH=%s,AVERAGE-BANDWIDTH=%s,RESOLUTION=%sx%s,CODECS="avc1.4d401f,mp4a.40.2"\n%s/index.m3u8\n' \
    "$bandwidth" "$bandwidth" "$width" "$resolution" "${height}p" >> "$master"
done

printf 'HLS master written to %s\n' "$master"
